# Generated by Django 3.1.1 on 2020-10-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_wishitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishitem',
            name='items',
        ),
        migrations.AddField(
            model_name='wishitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
    ]
